### ISSUE TITLE
Request timeout handling

### ISSUE THREAD

**Issue by weilu** [common-blockchain/common-blockchain#4]
Timeout in cb-blockr is currently hardcoded to 10 seconds. I have a case where a single batch request takes slightly longer than 10 seconds to return data which makes the app throw up. Should we expose timeout and allow it to be adjusted or should we make the library "smart" enough to catch timeout errors, extend timeout and retry?

**Comment by dcousens** [comment]
agreed with @jprichardson, probably best to make sure this is per implementation, not

**Comment by dcousens** [comment]
Resolved by https://github.com/dcousens/common-blockchain/commit/c2360e4ac87b76194f0dcb671c415837f02fdb0f.

**Comment by weilu** [comment]
No that doesn't resolve it. I'm not talking about test request timeouts. This issue is about http request timeout in the cb-foo implementation, for example, should we define something like `API.timeout` which is then used as the http request timeout in places like this: https://github.com/weilu/cb-blockr/blob/master/src/utils.js#L78

**Comment by dcousens** [comment]
@weilu I was thinking something along the lines of a https://github.com/dcousens/cb-node/blob/master/src/index.js#L66 option on the main object?

Will we need to provide other options in the future?

**Comment by weilu** [comment]
>  a timeout option on the main object?

I think that will do it for now.

> Will we need to provide other options in the future?

I recently added a proxyUrl to cb-blockr to get around a CORS issue: https://github.com/weilu/cb-blockr/commit/fa605b71cfd5c54e7b16521e4d60482ace121495. So yeah I think we should leave room for providing additional options in the future

**Comment by dcousens** [comment]
Perhaps a `xhrOptions` field?

**Comment by weilu** [comment]
works for me

**Comment by dcousens** [comment]
I've taken the approach of using `xhrOptions` on the top-level object in [`cb-node`](https://github.com/dcousens/cb-node/blob/master/src/index.js#L12-L15), and it appears to work relatively well.

The interesting question is whether or not we want to impose transport level parameters on our users.  For example, I may not use HTTP at all for a localized bitcoind node; so XHR makes little sense.

In this aspect, I'd actually vote against this option; since, its very much something that may be need to be configured for each API independently, and naturally only makes sense in that context.

**Comment by weilu** [comment]
> maybe not beyond using it as a 'recommended' option

My understanding is that it's an option that is applied on a "best effort" bases -- meaning when it's specified, if an API supports it, it will be applied, but if not it will just not be applied without warning or error. If that's the case, we are on the same page.

**Comment by jprichardson** [comment]
I think that any common blockchain implementation should take as options to the constructor. It allows any specific implementation to allow options outside of the spec. That leads me to... this really needs an official spec. I'll happily volunteer to be the one who writes it... hehehe. It'll have to wait a bit though due to other priories at the moment though.

**Comment by dcousens** [comment]
Closing as this has basically become an implementation detail.
